### ISSUE TITLE
pre-computed metadata can not download?

### ISSUE THREAD

**Issue by wolf943134497** [facebookresearch/map-anything#21]
Thanks for your great works!

Has anyone successfully downloaded the pre-computed metadata?

**Comment by Nik-V9** [comment]
Hi, are you referring to this issue?

https://huggingface.co/datasets/facebook/map-anything/discussions/1

I'm currently working on resolving this.

**Comment by wolf943134497** [comment]
Yes, that's the issue. Thank you for your efforts.

**Comment by Nik-V9** [comment]
I think the issue should be fixed now. Can you try accessing the metadata again?

**Comment by wolf943134497** [comment]
Thanks a lot !
I can download the dataset via git clone, but I still cannot download it through huggingface hub.
